-- Drop the legacy UNIQUE constraint on billing_subscriptions.stripe_customer_id.
--
-- The original schema (20260509030000_billing_subscriptions) modeled
-- billing as one subscription per organization, where each org had its
-- own Stripe Customer. UNIQUE on stripe_customer_id was correct then.
--
-- 20260513000000_billing_subscriptions_per_property moved us to one
-- subscription per property under a single org-shared Stripe Customer,
-- but never dropped the now-incorrect UNIQUE constraint. The result is
-- that the FIRST property in an org takes the lone allowed row with
-- that customer id, and every subsequent property's customer.subscription.*
-- webhook fails with SQLSTATE 23505 — exactly the bug we just hit on
-- Grand Hotel.
--
-- We keep the non-unique INDEX on stripe_customer_id (defined in
-- 20260512010000_billing_subscriptions_align.sql) so lookups by Customer
-- stay indexed. Uniqueness is governed by (property_id) only — that's the
-- primary key on this table.
--
-- The constraint name has historically been autogenerated:
--   billing_subscriptions_stripe_customer_id_key — the original UNIQUE in
--     20260509030000 declared inline on the column, which Postgres names
--     "<table>_<column>_key" by default.
-- Some environments may also carry the alternative spelling if the table
-- was recreated by an early migration; cover both by name.

alter table public.billing_subscriptions
  drop constraint if exists billing_subscriptions_stripe_customer_id_key;

-- Belt-and-suspenders: if for any reason a UNIQUE INDEX (rather than a
-- table-level constraint) was created with the same column-key name, drop
-- it too. INDEX names live in pg_class, not pg_constraint.
drop index if exists public.billing_subscriptions_stripe_customer_id_key;
